export const projects = [
  {
    title: "TRANQUILITY APP",
    subtitle: "CSS, HTML, JavaScript, External API",
    description: "The Tranquility app was created to give people an opportunity to take a break from the everyday demand in a fast paced enviroment. It allows the user to press a button that will generate a random inspirational quote, as well as a random picture of nature. I also added a journaling feature, where the user can journal some thoughts which will be saved in their local storage. This app utilizes Pixabay and Zen Quotes API.",
    image: "./tranquility_updated_speed.gif",
    link: "https://kimcapgab.github.io/Tranquility_App/",
    github: "https://github.com/kimcapgab/Tranquility_App",
    id: "1",
  },
  {
    title: "SHOP ECO APP",
    subtitle: "React, Airtable API, GET, POST, and PUT Requests, Material UI ",
    description: "Shop Eco is an Airtable and React build where the user is able to browse a variety of eco-friendly small businesses. At the homepage, the user is able to navigate shops based on the categories (Furniture, Clothing, and Candles). Each page will lead the user to eco-friendly shops that fit the category that was selected. The user is also able to submit a new shop that they would like to add to the existing list.",
    image: "./ShopEcogif.gif",
    link: "https://shop-eco.netlify.app/",
    github: "",
    id: "2",
  },
  {
    title: "YOUR CRAFT APP",
    subtitle: "React, Express, Mongoose, MongDB, GET, POST, PUT and Delete Requests",
    description: "Your Craft is an app that displays an inventory of craft beer, wines and liquors. This app was created to promote small locally owned Brewers, Distillers, and Wine Makers. It allows small businesses to add their products, a link to their website, as well as show details about the beverage.",
    image: "",
    link: "https://zealous-leavitt-47d043.netlify.app/",
    github: "",
    id: "3",
  },
  // {
  //   title: "",
  //   subtitle: "", 
  //   description: "",
  //   image: "",
  //   link: "",
  //   id: "4",
  // },
]